server:
  port: 8084

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mobiliz
    username: postgres
    password: ahmet1903
    jpa:
      show-sql: true

#logging:
#  level:
#    root: DEBUG

eureka:
  client:
    service-url:
      :defaultZone: http://localhost:8761/eureka/
